# Site settings
title: Practice Site Alyssa 
email: aruss947@gmail.com
description: My practice site. 
baseurl: "/Practice-Site-Alyssa"
twitter_username: 
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Alyssa Russell" # Set default author name
      categories: "dogs"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
